# Generated by Django 6.0.2 on 2026-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'fuel_stations',
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['state', 'city'], name='fuel_statio_state_8396aa_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_statio_latitud_c84538_idx'), models.Index(fields=['retail_price'], name='fuel_statio_retail__463e8c_idx')],
            },
        ),
    ]
